"""Initial migration with categories and transactions

Revision ID: 353e83e9a124
Revises: 
Create Date: 2026-05-04 15:27:19.617361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '353e83e9a124'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('recurring', sa.Boolean(), nullable=True))

    # Populate defaults for existing rows
    op.execute("UPDATE transactions SET currency = 'USD', recurring = 0")

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('currency', existing_type=sa.String(length=3), nullable=False)
        batch_op.alter_column('recurring', existing_type=sa.Boolean(), nullable=False)
        batch_op.alter_column('id', existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
        batch_op.alter_column('amount', existing_type=sa.REAL(), type_=sa.Numeric(precision=15, scale=2), existing_nullable=False)
        batch_op.alter_column('transaction_type', existing_type=sa.TEXT(), type_=sa.String(length=10), existing_nullable=False)
        batch_op.alter_column('category', existing_type=sa.TEXT(), type_=sa.String(length=120), existing_nullable=False)
        batch_op.alter_column('transaction_date', existing_type=sa.TEXT(), type_=sa.Date(), existing_nullable=False)
        batch_op.alter_column('created_at', existing_type=sa.TEXT(), type_=sa.DateTime(), existing_nullable=False, existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index('idx_transactions_date')
        batch_op.drop_index('idx_transactions_category')
        batch_op.create_index('idx_transactions_date_type', ['transaction_date', 'transaction_type'])
        batch_op.create_foreign_key('fk_transactions_categories', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_categories', type_='foreignkey')
        batch_op.drop_index('idx_transactions_date_type')
        batch_op.create_index('idx_transactions_date', ['transaction_date'])
        batch_op.create_index('idx_transactions_category', ['category'])
        batch_op.alter_column('created_at', existing_type=sa.DateTime(), type_=sa.TEXT(), existing_nullable=False, existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('transaction_date', existing_type=sa.Date(), type_=sa.TEXT(), existing_nullable=False)
        batch_op.alter_column('category', existing_type=sa.String(length=120), type_=sa.TEXT(), existing_nullable=False)
        batch_op.alter_column('transaction_type', existing_type=sa.String(length=10), type_=sa.TEXT(), existing_nullable=False)
        batch_op.alter_column('amount', existing_type=sa.Numeric(precision=15, scale=2), type_=sa.REAL(), existing_nullable=False)
        batch_op.alter_column('id', existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
        batch_op.drop_column('recurring')
        batch_op.drop_column('tags')
        batch_op.drop_column('currency')
        batch_op.drop_column('category_id')

    op.drop_table('categories')
    # ### end Alembic commands ###
