"""Add budgets table.

Revision ID: ced4bd2deb17
Revises: 353e83e9a124
Create Date: 2026-05-04 16:43:22.463705

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'ced4bd2deb17'
down_revision: str | Sequence[str] | None = '353e83e9a124'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
