"""Add automation_config table.

Revision ID: e7934e007a74
Revises: ced4bd2deb17
Create Date: 2026-05-04 15:45:24.173923

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e7934e007a74'
down_revision: str | Sequence[str] | None = 'ced4bd2deb17'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_type', sa.String(length=10), nullable=False),
    sa.Column('schedule_day', sa.Integer(), nullable=True),
    sa.Column('schedule_time', sa.String(length=5), nullable=False),
    sa.Column('export_format', sa.String(length=10), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_user', sa.String(length=255), nullable=True),
    sa.Column('smtp_password', sa.String(length=255), nullable=True),
    sa.Column('email_to', sa.String(length=255), nullable=True),
    sa.Column('email_subject', sa.String(length=255), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('automation_config')
    # ### end Alembic commands ###
